Title: ij.start.canon | Setup and download canon printer

Description : Use the Canon Print Inkjet or Selphy application to connect the Android device to your Canon printer. It also functions as a portal to manage all the Canon IJ Setup settings. You can also use the app to monitor the status of your print operation.
